from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(670, 480)
        self.CentralWidget = QtWidgets.QWidget(MainWindow)
        self.CentralWidget.setObjectName("CentralWidget")
        self.LeftFrame = QtWidgets.QFrame(self.CentralWidget)
        self.LeftFrame.setGeometry(QtCore.QRect(10, 10, 450, 420))
        self.LeftFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LeftFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LeftFrame.setObjectName("LeftFrame")
        self.TopFrame = QtWidgets.QFrame(self.LeftFrame)
        self.TopFrame.setGeometry(QtCore.QRect(0, 0, 450, 70))
        self.TopFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TopFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TopFrame.setObjectName("TopFrame")
        self.HappyPushButton = QtWidgets.QPushButton(self.TopFrame)
        self.HappyPushButton.setGeometry(QtCore.QRect(5, 15, 80, 40))
        self.HappyPushButton.setStyleSheet("background-color: rgb(129, 255, 124);")
        self.HappyPushButton.setObjectName("HappyPushButton")
        self.AngryPushButton = QtWidgets.QPushButton(self.TopFrame)
        self.AngryPushButton.setGeometry(QtCore.QRect(95, 15, 80, 40))
        self.AngryPushButton.setStyleSheet("background-color: rgb(255, 66, 94);")
        self.AngryPushButton.setObjectName("AngryPushButton")
        self.SadPushButton = QtWidgets.QPushButton(self.TopFrame)
        self.SadPushButton.setGeometry(QtCore.QRect(275, 15, 80, 40))
        self.SadPushButton.setStyleSheet("background-color: rgb(248, 255, 159);")
        self.SadPushButton.setObjectName("SadPushButton")
        self.NeutralPushButton = QtWidgets.QPushButton(self.TopFrame)
        self.NeutralPushButton.setGeometry(QtCore.QRect(185, 15, 80, 40))
        self.NeutralPushButton.setStyleSheet("background-color: rgb(138, 255, 238);")
        self.NeutralPushButton.setObjectName("NeutralPushButton")
        self.ResetPushButton = QtWidgets.QPushButton(self.TopFrame)
        self.ResetPushButton.setGeometry(QtCore.QRect(365, 15, 80, 40))
        self.ResetPushButton.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.ResetPushButton.setObjectName("ResetPushButton")
        self.BottomFrame = QtWidgets.QFrame(self.LeftFrame)
        self.BottomFrame.setGeometry(QtCore.QRect(0, 340, 450, 80))
        self.BottomFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BottomFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BottomFrame.setObjectName("BottomFrame")
        self.AudioFrame = QtWidgets.QFrame(self.BottomFrame)
        self.AudioFrame.setGeometry(QtCore.QRect(0, 0, 450, 40))
        self.AudioFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.AudioFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.AudioFrame.setObjectName("AudioFrame")
        self.AudioPlayPushButton = QtWidgets.QPushButton(self.AudioFrame)
        self.AudioPlayPushButton.setGeometry(QtCore.QRect(0, 4, 60, 32))
        self.AudioPlayPushButton.setObjectName("AudioPlayPushButton")
        self.AudioHorizontalSlider = QtWidgets.QSlider(self.AudioFrame)
        self.AudioHorizontalSlider.setGeometry(QtCore.QRect(65, 4, 310, 32))
        self.AudioHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.AudioHorizontalSlider.setObjectName("AudioHorizontalSlider")
        self.AudioTimeLabel = QtWidgets.QLabel(self.AudioFrame)
        self.AudioTimeLabel.setGeometry(QtCore.QRect(385, 10, 56, 20))
        self.AudioTimeLabel.setObjectName("AudioTimeLabel")
        self.ChangeAudioFrame = QtWidgets.QFrame(self.BottomFrame)
        self.ChangeAudioFrame.setGeometry(QtCore.QRect(0, 40, 450, 40))
        self.ChangeAudioFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ChangeAudioFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ChangeAudioFrame.setObjectName("ChangeAudioFrame")
        self.NextAudioPushButton = QtWidgets.QPushButton(self.ChangeAudioFrame)
        self.NextAudioPushButton.setGeometry(QtCore.QRect(350, 4, 100, 32))
        self.NextAudioPushButton.setObjectName("NextAudioPushButton")
        self.PreviousAudioPushButton = QtWidgets.QPushButton(self.ChangeAudioFrame)
        self.PreviousAudioPushButton.setGeometry(QtCore.QRect(0, 4, 100, 32))
        self.PreviousAudioPushButton.setObjectName("PreviousAudioPushButton")
        self.CentralFrame = QtWidgets.QFrame(self.LeftFrame)
        self.CentralFrame.setGeometry(QtCore.QRect(0, 70, 450, 270))
        self.CentralFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CentralFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CentralFrame.setObjectName("CentralFrame")
        self.RightWidget = QtWidgets.QWidget(self.CentralWidget)
        self.RightWidget.setGeometry(QtCore.QRect(470, 10, 190, 420))
        self.RightWidget.setObjectName("RightWidget")
        self.scrollArea = QtWidgets.QScrollArea(self.RightWidget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 190, 420))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 188, 418))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.CentralWidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 670, 24))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionSaveAs = QtWidgets.QAction(MainWindow)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionHappy = QtWidgets.QAction(MainWindow)
        self.actionHappy.setObjectName("actionHappy")
        self.actionAngry = QtWidgets.QAction(MainWindow)
        self.actionAngry.setObjectName("actionAngry")
        self.actionSad = QtWidgets.QAction(MainWindow)
        self.actionSad.setObjectName("actionSad")
        self.actionNeutral = QtWidgets.QAction(MainWindow)
        self.actionNeutral.setObjectName("actionNeutral")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSaveAs)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.HappyPushButton.setText(_translate("MainWindow", "Happy"))
        self.AngryPushButton.setText(_translate("MainWindow", "Angry"))
        self.SadPushButton.setText(_translate("MainWindow", "Sad"))
        self.NeutralPushButton.setText(_translate("MainWindow", "Neutral"))
        self.ResetPushButton.setText(_translate("MainWindow", "Reset"))
        self.AudioPlayPushButton.setText(_translate("MainWindow", "Play"))
        self.AudioTimeLabel.setText(_translate("MainWindow", "00:00:00"))
        self.NextAudioPushButton.setText(_translate("MainWindow", "Next"))
        self.PreviousAudioPushButton.setText(_translate("MainWindow", "Previous"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionSaveAs.setText(_translate("MainWindow", "Save As..."))
        self.actionHappy.setText(_translate("MainWindow", "Happy"))
        self.actionAngry.setText(_translate("MainWindow", "Angry"))
        self.actionSad.setText(_translate("MainWindow", "Sad"))
        self.actionNeutral.setText(_translate("MainWindow", "Neutral"))